### PR TITLE
chore: separate updatecli to its own pipeline

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR separates updatecli to its own pipeline and uses https://github.com/apps/jenkins-infra-updatecli instead of https://github.com/jenkins-infra-bot in updatecli values.

Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2778

### CODE REVIEW

**Comment by lemeurherve** [comment]
The updatecli pipeline fails as there is currently no `./updatecli/updatecli.d` folder.

**Comment by lemeurherve** [comment]
Tested https://github.com/jenkins-infra/pipeline-library/pull/870 with success, the pipeline doesn't fail anymore:
https://infra.ci.jenkins.io/job/updatecli/job/aws/job/PR-558/3/console
> WARNING: no ./updatecli/updatecli.d folder.

Reverting https://github.com/jenkins-infra/aws/pull/558/commits/77efcf2a6e27530f0745a159a712e6e2509c02ea

**Comment by lemeurherve** [comment]
> The updatecli pipeline fails as there is currently no `./updatecli/updatecli.d` folder.

New updatecli job triggered after https://github.com/jenkins-infra/pipeline-library/pull/870: ✅

**Review by dduportal — APPROVED** [review]
`No changes. Your infrastructure matches the configuration.`

**Review by dduportal — APPROVED** [review]

**Pull request merged**
